version: "3.5"
    
services:
  db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: bingogame
      MYSQL_USER: bingo
      MYSQL_PASSWORD: bingo
    ports:
    - "3306:3306"
  bingo-api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      MYSQL_URL: jdbc:mysql://db:3306/bingogame?autoReconnect=true&useSSL=false
      MYSQL_USER: bingo
      MYSQL_PASSWORD: bingo
    ports:
    - "9000:9000"
    depends_on:
    - db
    # entrypoint: ["sleep", "10000000"]
  # bingo-front-end:


volumes:
  db_data: {}

