version: "3.5"
    
services:
  db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: bingogame
      MYSQL_USER: bingo
      MYSQL_PASSWORD: bingo
    ports:
    - "3306:3306"

volumes:
  db_data: {}

